### ISSUE TITLE
YAMLException with !Sub

### ISSUE THREAD

**Issue by IPWright83** [eugene-manuilov/cfpack#12]
I seem to get an error trying to process my CloudFormation to do with the Sub command.

> ├─ Error processing /home/iw651/src/prototypes/esg-app-cms/cloudformation/cf/s3.yml template: YAMLException: unknown tag !<!Sub> at line 18, column 7:
│            PublicAccessBlockConfiguration:

The YAML I'm trying to process is like:

```
---
AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"

Parameters:
  EnvType:
    Type: String
    Default: "dev"

Resources:
  StrapiCMSAssetBucket:
    Type: "AWS::S3::Bucket"
    DeletionPolicy: Retain
    Properties:
      BucketName: !Sub
        - "my-test-strapi-assets-${EnvType}"
        - EnvType: !Ref EnvType
```
